name: check

on:
  push:
    branches-ignore: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ./.github/workflows/_setup.yml

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/.yarn/cache
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-nodemodules
      - name: Run build
        run: yarn build
        env:
          NEXT_PUBLIC_FIRST: ${{ vars.NEXT_PUBLIC_FIRST }}
          NEXT_PUBLIC_LAST: ${{ vars.NEXT_PUBLIC_LAST }}
          NEXT_PUBLIC_NICK: ${{ vars.NEXT_PUBLIC_NICK }}
          NEXT_PUBLIC_DEPLOY_TO: ${{ secrets.NEXT_PUBLIC_DEPLOY_TO }}
          NEXT_PUBLIC_SHOWDONATEMODAL: ${{ secrets.NEXT_PUBLIC_SHOWDONATEMODAL }}
          NEXT_PUBLIC_EMAIL: ${{ secrets.NEXT_PUBLIC_EMAIL }}
          NEXT_PUBLIC_XMPP: ${{ secrets.NEXT_PUBLIC_XMPP }}
          NEXT_PUBLIC_SIMPLEX: ${{ secrets.NEXT_PUBLIC_SIMPLEX }}
          NEXT_PUBLIC_MATRIX: ${{ secrets.NEXT_PUBLIC_MATRIX }}
          NEXT_PUBLIC_BTC: ${{ secrets.NEXT_PUBLIC_BTC }}
          NEXT_PUBLIC_ETH: ${{ secrets.NEXT_PUBLIC_ETH }}
          NEXT_PUBLIC_XMR: ${{ secrets.NEXT_PUBLIC_XMR }}